# Generated by Django 5.2.15 on 2026-06-17 09:19

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='external_url',
            field=models.URLField(blank=True, validators=[portfolio.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[portfolio.validators.validate_certificate_file_upload]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[portfolio.validators.validate_certificate_image_upload]),
        ),
    ]
