# Generated by Django 5.2.15 on 2026-06-18 05:27

import django.db.models.deletion
import django.utils.timezone
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_certificate_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('excerpt', models.TextField(max_length=520)),
                ('body', models.TextField()),
                ('key_takeaways', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_reading_time', models.PositiveSmallIntegerField(default=6)),
                ('seo_title', models.CharField(max_length=240)),
                ('meta_description', models.CharField(max_length=320)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', '-published_at', 'title'),
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='academic_connection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Learning'), ('mathematics', 'Mathematics'), ('sports', 'Sports Achievement')], db_index=True, default='technical', max_length=40),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='learning_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='result_display',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score_display',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='certificate',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('url', models.URLField(validators=[portfolio.validators.validate_http_url])),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='portfolio.blogpost')),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
    ]
